# Generated by Django 4.2.5 on 2023-09-24 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import indeed.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('unique_key', models.CharField(default=indeed.models.generate_unique_key, max_length=36, unique=True)),
            ],
        ),
    ]
